### ISSUE TITLE
crash with extrautils clock on drains

### ISSUE THREAD

**Issue by TheNimbleNinja** [MJRLegends/TinkersExtras#10]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
crash with extrautills clock on the tinkers pipe that drains fluids from the drain
### Steps to Reproduce Issue
1. [First step]
2. [Second step]

crash with extrautills clock on the tinkers pipe that drains fluids from the smetery drain

https://paste.dimdev.org/ujaburexoh.mccrash

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

tinkers extra-1.12.2-1.0.7

**Where did this bug happen:** [Single Player or Server]

single player and most likey server also

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Wow so it seems that redstone clock triggers the event even if its not making anything lol what. I can fix thanks

**Comment by MJRLegends** [comment]
Updating being uploaded as we speak
