### ISSUE TITLE
Crash when I try to create a bucket with the tinker

### ISSUE THREAD

**Issue by HurtsAsHell** [MJRLegends/TinkersExtras#11]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Steps to Reproduce Issue
1. Smelt the ingot
2. Place the bucket on the table
3. Right click on faucet
4. Crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/H5SKtSuw

**Where did this bug happen:** [Single Player]

I'm pretty sure it's an extra tinker problem, I've had other people try to use bucket crafting and no extra tinker goes, please fix it as soon as possible or I'm stuck

**Comment by MJRLegends** [comment]
Update will be out within the next hour to fix this, thank you :P

**Comment by MJRLegends** [comment]
Updated released

**Comment by HurtsAsHell** [comment]
oki, thanks
