### ISSUE TITLE
Creating certain tool parts and tool casts in the smeltery crashes the game. (Bolt core)

### ISSUE THREAD

**Issue by SirAron111** [MJRLegends/TinkersExtras#12]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
Creating certain tool parts and tool casts in the smeltery crashes the game. With the new version since adding the smeltery support certain items crash the game when trying to make casts or parts with tinkers extras installed.
I reported a similar thing earlier this time it happens with the bolt core creation when trying to pure metal over an arrow shaft.
Here is a list of things that crash:
Creating Bold core when placing a arrow shaft on the casting table and trying to pure any molten metal on it = crash
.......
### Steps to Reproduce Issue
1. Place arrow shaft of any kind in the casting table
2. Try to pure anything from the smeltery onto the arrow shaft.
3. Watch it crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

https://pastebin.com/qsb7nzrV

**Screenshots (if applicable):** 
Not needed

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
TinkersExtras-1.12.2-1.0.8.jar 

**Where did this bug happen:** [Single Player or Server]
single player and server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please post a crash log with the latest version

**Comment by SirAron111** [comment]
A it’s all ok. The newest version doesn’t throw the problem for the bolts the guy giving me the reports apparently tested it only with the TinkersExtras-1.12.2-1.0.8.jar two times thinking he tested it with the TinkersExtras-1.12.2-1.0.9.jar one as well. I really have to double check everything myself before reporting it sry.

**Comment by MJRLegends** [comment]
No problem
