### ISSUE TITLE
(Minor/Question) Disabled modifiers are not hidden from the Tinkers book

### ISSUE THREAD

**Issue by cosmicdan** [MJRLegends/TinkersExtras#14]
Howdy, 

Great mod, I especially love how disabled materials and traits are automatically hidden from the book. But this does not occur for disabled modifiers - they're still visible (but the disable is working OK as expected).

So, quick question: is this a limitation of Tinkers Construct itself or a TODO on your end?

Cheers!

**Comment by MJRLegends** [comment]
Will take a look but really depends if the API allows me too, sounds like tinkers doesnt pull a live list for the book. 

I will see what i can do

**Comment by cosmicdan** [comment]
> Will take a look but really depends if the API allows me too, sounds like tinkers doesnt pull a live list for the book.

Everything else updated which was awesome, if that's not something you did at your end then yeah I suppose it's a TiC thing. If so, I'll bug them about it (or fork it and do a PR myself if I can figure it out heh).

**Comment by MJRLegends** [comment]
TinkersConstruct can only fix this sorry
