### ISSUE TITLE
Enhancement: adjustable Modifier limit.

### ISSUE THREAD

**Issue by SirAron111** [MJRLegends/TinkersExtras#16]
At the moment you can just disable a modifier completely like Necrotic bones etc but i would like to be able to set limits for them and not completely disable them just so it’s not to op to when I have leveling and extra modifiers free. Like only 50% durability not unbreaking or only 10% life steal not 100% etc so limiting the number of X modifier to be put on a tool and instead increase others like more sharpness to help with scaling health packs etc. Would that be possible or can you just flat out disable it.

**Comment by paulgb434** [comment]
Not exactly a solution, but if you want you can customize the specific modifiers that a material has in the mod "Tweakers' Construct" on Curseforge.

**Comment by MJRLegends** [comment]
Will be added in next update

**Comment by MJRLegends** [comment]
Update released
