### ISSUE TITLE
[Suggestion] Disable specific tool parts rather than tool material type.

### ISSUE THREAD

**Issue by UnlimatedStone9** [MJRLegends/TinkersExtras#17]
I think it would be quite a useful addition if you could disable the ability to swap specific tool parts, or tool part categories, rather than the entire material type.
For example I could blacklist tool_rod:iron, this would allow me to prevent swapping tool rods with iron tool rods, however it wouldn't prevent doing so with pickaxe heads, shovel heads, or any other non blacklisted part of the same material type.
Additionally the ability to blacklist the entire category of tool_rod, would allow me to swap all other tool parts of any material that isn't blacklisted already, but would not be able to swap tool rods.

**Comment by MJRLegends** [comment]
There already is this option below, isnt this what you want?

```
# Use part name and material name in the Format: part_name:material_name Example: pick_head:stone [default: ]
    S:"List of Parts that cant be created in the Part Builder (based on certain Material type)" <
        pick_head:stone
     >
```

**Comment by UnlimatedStone9** [comment]
Unfortunately no, that disables the recipe for said part, however what I'm looking for is a way to disable swapping that tool part with another (replacing a stone pick head with an iron one on the tool forge, etc).

**Comment by MJRLegends** [comment]
Yea sorry i see what you mean now. Yea sure that can be added, didnt know that was missing tbh

**Comment by UnlimatedStone9** [comment]
Yeah, I noticed it was a little inconsistent with the other configs, thanks!

**Comment by MJRLegends** [comment]
Will be in the next update

**Comment by MJRLegends** [comment]
Update released
