### ISSUE TITLE
Modifier Issue

### ISSUE THREAD

**Issue by Override5** [MJRLegends/TinkersExtras#20]
Im making this avaiable on every tinkers construct based mod i have installed in my pack.

there is an issue trying to add more then 9 modifiers to a tool or armor. Attempting to put more modifiers gets This error. Ive tried to look in the configs, but i found nothing. Also, There are still modifier slots avaiable.

Curretly, the tinkers mods installed are

Tinkers Construct 2.13.0.183
Construct's Armory 1.2.5.4
PlusTiC 8.0.0.1
Tinkers Tool Leveling 1.1.0
Tinkers Extras 1.1.0
Tinker I/O rw2.8.2
Tinkers Complement 0.4.3
![image](https://user-images.githubusercontent.com/69968054/111251035-90d92900-8662-11eb-8b5f-506253a79933.png)

**Comment by MJRLegends** [comment]
This is a config option to limit the amount of modifiers so all intended. You can change the amount in the config

**Comment by Override5** [comment]
Where can i find the config?

**Comment by MJRLegends** [comment]
Same place as all the other mod configs

**Comment by Override5** [comment]
Ok, and what line in the config is it? ive looked through it all and couldnt find anything.

**Comment by MJRLegends** [comment]
https://docs.mjrlegends.com/General%20Minecraft/config/

**Comment by Override5** [comment]
![image](https://user-images.githubusercontent.com/69968054/111260236-92abe800-8674-11eb-81ed-5eb5249fc3d9.png)
![image](https://user-images.githubusercontent.com/69968054/111260267-9b9cb980-8674-11eb-8906-35c2f5d25f6a.png)

This is what im seeing. I cant see anything limiting the amount of modifiers

**Comment by Override5** [comment]
Never mind, I see it. Line 21. It set to 100, so my issue is still an issue

**Comment by MJRLegends** [comment]
Have you restarted your client since the change?

Also if your playing on a server make sure you make the change on their too and restart the server also

**Comment by Override5** [comment]
Im the server admin, i changed it to 100 in a previous version of the server, but it never applied by the looks of it. maybe chaning it to -1 will disable it all together?
