### ISSUE TITLE
Blacklisting Replacement Parts based on Material not working

### ISSUE THREAD

**Issue by merdink** [MJRLegends/TinkersExtras#22]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Adding to the config entry for "List of parts which cant be used as replacements on tools (based on certain Material type)" seems to not do anything. Does not stop you from replacing with the material/part you blacklist in the config.

### Steps to Reproduce Issue
1. Added example pick_head:stone to replacement blacklist entry in config
2. Loaded up Minecraft
3. Make a Tinkers pickaxe
4. Make a stone pickaxe head
5. The tool station/forge will not stop you from making the replacement

**Crash log/Log (if applicable):** n/a

**Screenshots (if applicable):** 
![image](https://github.com/MJRLegends/TinkersExtras/assets/4110814/23d91b9c-039e-488f-809c-4d2de9d4fe0c)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.1.0

**Where did this bug happen:** Single Player

### Additional Information
"List of Parts that cant be created in the Part Builder (based on certain Material type)" and "List of Tools that cant be created (based on certain Material type)" work fine. I did notice "List of Tools that cant be created (based on certain Material type)" only seems to work if the first part is of the blacklisted material but I probably should post a different issue for that. (Like if you did mattock:stone, you could still craft if the first part wasn't stone but the second part was)

**Comment by MJRLegends** [comment]
Please could you provide your full client log files and Tinkers construct version

**Comment by merdink** [comment]
[debug.log](https://github.com/MJRLegends/TinkersExtras/files/13220276/debug.log)

Tinkers Construct 1.12.2 Version 2.13.0.183

**Comment by MJRLegends** [comment]
Please can you also send a copy of your TinkersExtra config file and screenshots of the pickaxe, and part your replacing with as im having trouble reproducing this issue when testing.

**Comment by merdink** [comment]
https://pastebin.com/P7UZmKzt

At work so I'm unable to get screenshots at the moment.

**Comment by MJRLegends** [comment]
Thank you for proving the requested resources, im really having a hard time reproducing the issue.

Please can you provide your CraftTweaker scripts containing the Tinkers Extras lines

**Comment by MJRLegends** [comment]
Thank you for proving the requested resources, im really having a hard time reproducing the issue.

**Comment by MJRLegends** [comment]
Please can you send over a copy of your current Tinkers Extras config

**Comment by merdink** [comment]
It hasn't changed from what the pastebin has.

**Comment by MJRLegends** [comment]
Thank you for the reply, i have found the issue. I will get this fixed thank you

**Comment by MJRLegends** [comment]
Mod Update has been pushed to curseforge, it will be available on https://legacy.curseforge.com/minecraft/mc-mods/tinkersextras/files/4833503 once Curseforge appoves.

Thank you so much for working with me on finding the root of the bug,
