### ISSUE TITLE
Modifiers material to be disabled 

### ISSUE THREAD

**Issue by MrLador** [MJRLegends/TinkersExtras#3]
I wanted to disable the modifier of the wood is ecological, which has the properties of a recovery tool.
I used a string in the config:
S:"List of Modifiers to be disabled" <
	ecological
     >
But it doesn't work! Although the list of betony as a modifier: tinkersextras: Modifier: ecological.
Forge: 1.12.2-14.23.3.2655
TConstruct: 1.12.2-2.9.1.65
TinkersExtras: 1.12.2-1.0.3

**Comment by MJRLegends** [comment]
It seems, that this modifier isn't addable modifier as such like the others and you gain the ecological one from just using wooden tools, the modifier disabling is only for things like Mending Moss, Luck, Sharpness, Smite, Haste and so on :D

**Comment by MJRLegends** [comment]
Due to it being this way, Sorry but you wont be able to disable it :D
