### ISSUE TITLE
[Suggestion] Add support for disabling traits

### ISSUE THREAD

**Issue by MrLador** [MJRLegends/TinkersExtras#4]
(Edited by MJRLegends)

Please add the ability to disable the traits
Author Tinkers Construct wrote that it can be disabled using a third-party mod: 
https://github.com/SlimeKnights/TinkersConstruct/issues/3253

This will be a very useful feature for creating balanced modpacks.

**Comment by MrLador** [comment]
When can you add this feature?

**Comment by MJRLegends** [comment]
I've added the feature and the update has been released :P enjoy
