### ISSUE TITLE
Tools and materials from the addon Ender IO for Tinkers Construct are not disabled.

### ISSUE THREAD

**Issue by MrLador** [MJRLegends/TinkersExtras#6]
Materials from Ender IO when added to the shut-down materials simply do not work.

**Comment by MJRLegends** [comment]
You need to give more detail on the issue. Your one line isnt going to cut it

**Comment by MrLador** [comment]
I added to "List of Materials to be disabled" and these materials will not be disabled from Ender IO.
energetic_alloy
vibrant_alloy
redstone_alloy
conductive_iron
pulsating_iron

**Comment by MJRLegends** [comment]
Sorry for the delay, im currently looking at the issue.

**Comment by MJRLegends** [comment]
Please report to Ender IO, as im just listening on a Tinkers Construct event, and it seems Ender IO doesnt fire this event?

Here is the proof, these are all the ones thats seen by the event:

```
Material: wood
Material: stone
Material: flint
Material: cactus
Material: bone
Material: obsidian
Material: prismarine
Material: endstone
Material: sponge
Material: firewood
Material: iron
Material: pigiron
Material: knightslime
Material: slime
Material: blueslime
Material: magmaslime
Material: netherrack
Material: cobalt
Material: ardite
Material: manyullyn
Material: copper
Material: bronze
Material: lead
Material: silver
Material: electrum
Material: steel
Material: string
Material: slimevine_blue
Material: slimevine_purple
Material: vine
Material: blaze
Material: reed
Material: ice
Material: endrod
Material: feather
Material: slimeleaf_blue
Material: slimeleaf_orange
Material: slimeleaf_purple
Material: leaf
```

**Comment by MJRLegends** [comment]
Please let them know they can contact me if they need anything from me/need me to do on my side

**Comment by HenryLoenwind** [comment]
Which event? `MaterialEvent.MaterialRegisterEvent`? That one should be fired regularly...

![image](https://user-images.githubusercontent.com/1485873/48978653-f62e3800-f0ae-11e8-821e-b041ec4d88fa.png)

**Comment by MJRLegends** [comment]
Yeah thats the event im using for this. And from a code point of view im registering my handler for this event in the pre init so i dont think order would br a issue unless ender io does register its tinkers stuff in the pre init and just happens to run before my handler runs

**Comment by HenryLoenwind** [comment]
There we have it...

![image](https://user-images.githubusercontent.com/1485873/48980411-d0159180-f0c8-11e8-9933-ad70a0b4dfec.png)

I'd recommend you use `@EventBusSubscriber` to register your event handler. That way you never miss an event that is fired "too early".

(It'd be even better if TiC was to use the `Register<>` event for materials instead of us having to call in at weird times. But that'd be a major change to their registration system...)

**Comment by MJRLegends** [comment]
Mod integration stuff should always be done in the post init tbh

**Comment by MJRLegends** [comment]
Im willing to do after:enderio if ender io registers mod integration stuff in pre init
