### ISSUE TITLE
[ Bug ] The creation of part doesnt disable

### ISSUE THREAD

**Issue by HurtsAsHell** [MJRLegends/TinkersExtras#8]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [I think yes]

### Description of Issue
I want to delete the creation of part from smeltery and i wrote this **S:"List of Parts based on certain Materials that cant be created" <pick_head:iron>**

### Steps to Reproduce Issue
Add to *S:"List of Parts based on certain Materials that cant be created" <>* this **<pick_head:iron>**

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.0.2]

**Where did this bug happen:** [Single Player and server too i think]

### Additional Information
This is my [.cfg](https://pastebin.com/0c7UwUjM) file

**Comment by HurtsAsHell** [comment]
I sincerely hope you're not screwed, and also would be a nice addition to your mod

**Comment by HurtsAsHell** [comment]
I'm sorry if I ask you, but I'm waiting for this feature. Will you work on it? (for both issues)

**Comment by MJRLegends** [comment]
Will take a look at doing to right now for you

**Comment by HurtsAsHell** [comment]
ok, thanks

**Comment by MJRLegends** [comment]
Seems what i can do right now. Is make a config setting for disabling casts completely. Having a hard time using there events to get any details from them. Awaiting a reply from them on it..

**Comment by MJRLegends** [comment]
Wait ignore my above comment i can make it work i have just worked it out

**Comment by HurtsAsHell** [comment]
lol, ok

**Comment by MJRLegends** [comment]
Btw, This is what the config will look like after the update 
https://pastebin.com/pe6A4C6n

**Comment by MJRLegends** [comment]
Any more requests for features/config options before i push this update? @HurtsAsHell

**Comment by HurtsAsHell** [comment]
so with this update can I disable the creation of the iron pickaxe from the smeltery, for example?

**Comment by MJRLegends** [comment]
Well you can either disable the certain parts all together or a part based on material, same as the part builder. Tools are made in the tool station.

**Comment by HurtsAsHell** [comment]
I think I did not understand but I will adapt

**Comment by MJRLegends** [comment]
These are the options you have to disable things for smeltery
```

# Will only disable the creation not the existing of the parts
B:"Disable Ability to Create All Parts in the Smeltery Casting table"=false

```
    # Use part type name (Use F3 + H to show unlocalized names on parts to find there names, will be the name after the : ) Example: pick_head [default: ]
    S:"List of Parts that cant be created in the Smeltery Casting table" <
        pick_head
     >

    # Use part name and material name in the Format: part_name:material_name Example: pick_head:stone [default: ]
    S:"List of Parts that cant be created in the Smeltery Casting table (based on certain Material type)" <
        axe_head:iron
     >

**Comment by HurtsAsHell** [comment]
ooooh, okay. It's perfect

**Comment by MJRLegends** [comment]
Is there anything you would like in terms of config options, apart from #7 that one i might not add since it will be more messy than good?

**Comment by HurtsAsHell** [comment]
at the moment nothing comes to mind, in case I will write to you in the future. thank you so much

**Comment by MJRLegends** [comment]
Ok will push the update now

**Comment by HurtsAsHell** [comment]
for #7 7, if I have time, I can try it with a pr

**Comment by MJRLegends** [comment]
Update it now on curseforge

**Comment by HurtsAsHell** [comment]
thanks
