### ISSUE TITLE
List of Parts that cant be created in the Part Builder (based on certain Material type) option causing a crash

### ISSUE THREAD

**Issue by SirAron111** [MJRLegends/TinkersExtras#9]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
Trying to use the new version results in a crash every time I add a material to a part builder. Be it disabled or not disabled.
Things used like this.
    # Use part name and material name in the Format: part_name:material_name Example: pick_head:stone [default: [Ljava.lang.String;@1b43bcb6]
    S:"List of Parts that cant be created in the Part Builder (based on certain Material type)" <
        pick_head:stone
        pick_head:netherrack
        pick_head:cactus
        pick_head:flint
        pick_head:bone
        pick_head:prismarine
        pick_head:livingwood
        sharpening_kit:stone
        sharpening_kit:netherrack
        sharpening_kit:cactus
        sharpening_kit:flint
        sharpening_kit:bone
        sharpening_kit:prismarine
        sharpening_kit:livingwood
     >

---------- This will than crash the game when trying to make anything in the part builder

### Steps to Reproduce Issue
1. [First step] update from TinkersExtras-1.12.2-1.0.5.jar to TinkersExtras-1.12.2-1.0.6.jar and let a new config generate
2. [Second step] fill in any of the config options like done before
3. try to add cobble or anything disabled to a part builder that has a stancil and it crashes

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
TinkersExtras-1.12.2-1.0.6.jar
**Where did this bug happen:** [Single Player or Server]
single player and server
### Additional Information
https://pastebin.com/yAnK42fa here is the crash report

**Comment by MJRLegends** [comment]
Fixed version will be out in the next hour

**Comment by MJRLegends** [comment]
Update is rolling out as we speak
